spring:
  server:
    port: $PORT
  datasource:
    url: jdbc:h2:mem:bibliotecadb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true