spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${dbusername}
    password: ${dbpassword}
    driverClassName: org.postgresql.Driver
  jpa:
    database:
      platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    locations:
      classpath:/db_migrations
server:
  port: ${PORT:8080}

