spring:
  datasource:
    platform: postgres
    url: ${databaseURL}
    username: ${dbusername}
    password: ${dbpassword}
    driverClassName: ${dbDriverClassName}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
  flyway:
    locations:
      classpath:/db_migrations
server:
  port: ${PORT:8080}

