spring:
  datasource:
    platform: postgres
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
flyway:
  check-location: true
  locations: classpath:db/migration
server:
  port: ${PORT:8080}

