spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD]
    driverClassName: org.postgresql.Driver
  jpa:
    database:
      platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
flyway:
  check-location: true
  locations: classpath:db/migration
server:
  port: ${PORT:8080}

