version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: gradle:alpine
    steps:
      - checkout
      - run: ./gradlew bootJar
      - persist_to_workspace:
          root: ./
          paths:
            - build/
            - .gradle/
